#!/bin/bash
exec /opt/meditate/virtualenv/bin/gunicorn --pythonpath /opt/meditate/site/ \
	-e DJANGO_SETTINGS_MODULE=meditate.settings_deploy \
	--log-file /var/log/gunicorn_meditate.log --log-level debug \
    -b 127.0.0.1:8001 meditate.wsgi
