#!/bin/bash
exec /opt/meditate/virtualenv/bin/gunicorn --pythonpath /opt/meditate/site/ \
	-e DJANGO_SETTINGS_MODULE=meditate.settings \
	--log-file /var/log/gunicorn_tonetutor.log --log-level=debug \
    -b 127.0.0.1:8001 meditate.wsgi
