# Generated by Django 2.0 on 2017-12-23 01:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meditate', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='img',
            field=models.CharField(max_length=100),
        ),
    ]
