# Generated by Django 2.0 on 2017-12-23 02:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('meditate', '0002_auto_20171223_0138'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='SaleItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted', models.BooleanField(default=False)),
                ('name', models.CharField(max_length=80, unique=True)),
                ('desc', models.CharField(max_length=500)),
                ('img', models.CharField(max_length=100)),
                ('price', models.DecimalField(decimal_places=2, max_digits=3)),
            ],
        ),
        migrations.RemoveField(
            model_name='cartitem',
            name='coupons',
        ),
        migrations.RemoveField(
            model_name='cartitem',
            name='item',
        ),
        migrations.RemoveField(
            model_name='cartitem',
            name='order',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='sessionid',
            new_name='sessionId',
        ),
        migrations.AlterField(
            model_name='coupon',
            name='items',
            field=models.ManyToManyField(to='meditate.SaleItem'),
        ),
        migrations.DeleteModel(
            name='CartItem',
        ),
        migrations.DeleteModel(
            name='Item',
        ),
        migrations.AddField(
            model_name='orderitem',
            name='coupons',
            field=models.ManyToManyField(to='meditate.Coupon'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='order',
            field=models.ForeignKey(on_delete='cascade', to='meditate.Order'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='saleItem',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='meditate.SaleItem'),
        ),
    ]
