# Generated by Django 2.0 on 2018-01-20 03:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('meditate', '0004_orderitem_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='paymentConfirm',
            field=models.CharField(default=None, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='meditate.Order'),
        ),
    ]
