# Generated by Django 2.0 on 2018-01-20 04:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meditate', '0005_auto_20180120_0348'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='paymentConfirm',
            new_name='paymentId',
        ),
    ]
