# Generated by Django 2.0 on 2018-01-20 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meditate', '0006_auto_20180120_0407'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=3),
        ),
    ]
