# Generated by Django 2.0 on 2018-01-20 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meditate', '0007_order_total'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
    ]
