# Generated by Django 2.0 on 2018-01-24 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meditate', '0008_auto_20180120_0434'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='paymentProvider',
            field=models.CharField(default='', max_length=6),
        ),
    ]
