# Generated by Django 2.0 on 2018-03-12 19:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('meditate', '0009_order_paymentprovider'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderAddress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('phone', models.CharField(blank=True, max_length=18, null=True)),
                ('addr1', models.CharField(max_length=80)),
                ('addr2', models.CharField(max_length=80)),
                ('city', models.CharField(max_length=40)),
                ('state', models.CharField(max_length=2)),
                ('country', models.CharField(max_length=30)),
                ('zip', models.CharField(max_length=7)),
            ],
        ),
        migrations.AddField(
            model_name='saleitem',
            name='needsAddress',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='saleitem',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=4),
        ),
        migrations.AddField(
            model_name='order',
            name='address',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='meditate.OrderAddress'),
        ),
    ]
