# Generated by Django 2.0 on 2018-03-29 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meditate', '0010_auto_20180312_1908'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='processed',
            field=models.BooleanField(default=False),
        ),
    ]
