# Generated by Django 2.0 on 2018-03-29 19:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meditate', '0011_order_processed'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderaddress',
            old_name='zip',
            new_name='postal_code',
        ),
    ]
