# Generated by Django 2.0 on 2018-04-05 00:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meditate', '0012_auto_20180329_1926'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reflection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('content', models.TextField()),
                ('pub_time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
