# Generated by Django 2.0 on 2018-04-05 02:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meditate', '0013_reflection'),
    ]

    operations = [
        migrations.AddField(
            model_name='reflection',
            name='title_slug',
            field=models.CharField(blank=True, default='', editable=False, max_length=100),
        ),
        migrations.AlterField(
            model_name='reflection',
            name='pub_time',
            field=models.DateTimeField(),
        ),
    ]
