# Generated by Django 2.0 on 2018-04-13 01:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meditate', '0014_auto_20180405_0214'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reflection',
            name='title_slug',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='saleitem',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
    ]
