# Generated by Django 2.0 on 2018-04-13 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meditate', '0015_auto_20180413_0115'),
    ]

    operations = [
        migrations.CreateModel(
            name='Visit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip4', models.CharField(max_length=15)),
                ('ip6', models.CharField(max_length=39)),
                ('timestamp', models.DateTimeField()),
                ('page', models.CharField(max_length=20)),
            ],
        ),
    ]
