# Generated by Django 2.0 on 2018-04-15 00:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meditate', '0016_visit'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='downloadKey',
            field=models.CharField(default='', max_length=12),
        ),
        migrations.AddField(
            model_name='order',
            name='paymentTimestamp',
            field=models.DateTimeField(default=datetime.datetime.utcnow),
        ),
        migrations.AddField(
            model_name='saleitem',
            name='downloadable',
            field=models.FileField(blank=True, default=None, null=True, upload_to=''),
        ),
    ]
