# Generated by Django 2.0 on 2018-04-17 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meditate', '0017_auto_20180415_0020'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='paymentTimestamp',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='saleitem',
            name='downloadable',
            field=models.FileField(blank=True, default='', upload_to=''),
        ),
    ]
