# Generated by Django 2.0 on 2018-05-08 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meditate', '0019_auto_20180420_0001'),
    ]

    operations = [
        migrations.AddField(
            model_name='saleitem',
            name='sitype',
            field=models.CharField(choices=[('book', 'book'), ('mentorying', 'mentoring')], default='', max_length=20),
            preserve_default=False,
        ),
    ]
